Repository openebs/cstor-csi, pull requests merged in 2019-05, with the labels that each got.

#5 fix(build): updates buildscript to generate driver image
  .gitignore
  BUILDMETA
  Makefile
  buildscripts/build.sh
  buildscripts/csi-driver/Dockerfile
  pkg/generated/clientset/core/internalclientset/clientset.go
  pkg/generated/clientset/core/internalclientset/fake/clientset_generated.go
  pkg/generated/clientset/maya/internalclientset/clientset.go
  pkg/generated/clientset/maya/internalclientset/fake/clientset_generated.go
Labels: bug, type: Build

#3 chore(lint): add travis, bettercodehub and golangci integrations
  .bettercodehub.yml
  .golangci.yml
  .travis.yml
Labels: type: Lint

#6 fix(version): update Version file path and correct a typo
  cmd/main.go
  pkg/apis/openebs.io/core/v1alpha1/register.go
  vendor/github.com/openebs/maya/LICENSE
  vendor/github.com/openebs/maya/cmd/mayactl/LICENSE
  vendor/github.com/openebs/maya/pkg/version/version.go
Labels: bug

#8 refactor(driver): update driver code to follow idiomatic style
  Gopkg.lock
  cmd/main.go
  pkg/apis/openebs.io/core/v1alpha1/csivolume.go
  pkg/apis/openebs.io/core/v1alpha1/zz_generated.deepcopy.go
  pkg/driver/v1alpha1/controllerserver.go
  pkg/driver/v1alpha1/driver.go
  pkg/driver/v1alpha1/identityserver.go
  pkg/driver/v1alpha1/nodeserver.go
  pkg/iscsi/v1alpha1/iscsi_extra_utils.go
  pkg/iscsi/v1alpha1/mount.go
  pkg/payload/v1alpha1/response.go
  pkg/utils/v1alpha1/kubernetes.go
  pkg/utils/v1alpha1/utils.go
  pkg/volume/v1alpha1/build.go
  pkg/volume/v1alpha1/buildlist.go
  pkg/volume/v1alpha1/kubernetes.go
  pkg/volume/v1alpha1/volume.go
Labels: type: IdiomaticStandards

#9 refactor(idiomatic): update provisioning code to follow standard practices
  README.md
  pkg/apis/openebs.io/core/v1alpha1/csivolume.go
  pkg/apis/openebs.io/core/v1alpha1/zz_generated.deepcopy.go
  pkg/driver/v1alpha1/controllerserver.go
  pkg/utils/v1alpha1/maya.go
  pkg/volume/v1alpha1/volume.go
Labels: type: IdiomaticStandards
